"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

from functools import reduce
import operator

def fibonacci(limit: int):
        a, b = 1, 2
        while a < limit:
                yield a
                a, b = b, a + b

def is_even(x: int):
        return x % 2 == 0

even_fibonacci_terms = filter(is_even, fibonacci(4_000_000))
res = reduce(operator.add, even_fibonacci_terms)

print(res) # 4613732
