package euler;

import java.util.stream.IntStream;

// https://projecteuler.net/problem=2
// https://oeis.org/A000045 -- Fibonacci numbers.

/*
 * <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
 * <p class="center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
 * <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
 */

public class P2EvenFibonacciNumbers {

    public static void main(String[] args) {
        System.out.println(procedural()); // 4613732
        System.out.println(functional()); // 4613732
    }

    static int procedural() {
        int p = 1;
        int f = 2;
        int sum = 0;
        for (int n; f < 4_000_000; n = f + p, p = f, f = n) {
            if (f % 2 == 0) {
                sum += f;
            }
        }
        return sum;
    }

    static int p = 1;

    static int functional() {
        return IntStream
                .iterate(2, f -> f < 4_000_000,
                        P2EvenFibonacciNumbers::fibonacciNext)
                .filter(f -> f % 2 == 0)
                .sum();
    }

    static int fibonacciNext(int f) {
        int n = f + p;
        p = f;
        f = n;
        return f;
    }

}
